global:
  nodeSelector: {}
  affinity: {}
  tolerations: {}

OPENELIS_APPLICATION_DATA_DIRECTORY: /openmrs/data

replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmni
  name: OpenElis
  tag: latest

config:
  OPENELIS_IMAGE_TAG: latest
  OPENELIS_DB_SERVER: ""
  OPENELIS_DB_NAME: ""
  OPENMRS_ATOMFEED_USER: ""
  OPENMRS_ATOMFEED_PASSWORD: ""
  OPENELIS_DB_USER: ""
  OPENMRS_HOST: ""
  OPENMRS_PORT: ""
    
secrets:
  OPENELIS_DB_USER: ""
  OPENELIS_DB_PASSWORD: ""
  OPENMRS_HOST: ""
  OPENMRS_ATOMFEED_USER: ""
  OPENMRS_ATOMFEED_PASSWORD: ""


service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  #  minReplicas: 1
  #  maxReplicas: 5
  #  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes:
  patientDocuments:
    capacity: "2Gi"
    claimName: openmrs-document-images-pvc
  patientImages:
    capacity: "2Gi"
    claimName: openmrs-patient-images-pvc
  initializerChecksums:
    capacity: "1Gi"
  clinicalForms:
    capacity: "1Gi"
  uploadedResults:
    capacity: "2Gi"
  uploadedFiles:
    capacity: "2Gi"  

nodeSelector: {}
affinity: {}
tolerations: {}
