apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.OPENELIS_DB_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.OPENELIS_DB_PASSWORD | b64enc | quote}} 
  OPENMRS_HOST: {{ .Values.secrets.OPENMRS_HOST | b64enc | quote}}
  OPENMRS_ATOMFEED_USER: {{ .Values.secrets.OPENMRS_ATOMFEED_USER }}
  OPENMRS_ATOMFEED_PASSWORD: {{ .Values.secrets.OPENMRS_ATOMFEED_PASSWORD }}
  